# docker-compose.yml
# 2023-06-23 | CR
#

version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: lnmp_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${BASE_DIR}/html:/usr/share/nginx/html
      - ${BASE_DIR}/nginx-conf:/etc/nginx/conf.d
      - ${BASE_DIR}/ssl-certs:/etc/nginx/ssl-certs
    depends_on:
      - php

  php:
    # image: php:8-fpm
    build: ./php
    container_name: lnmp_php
    volumes:
      - ${BASE_DIR}/html:/usr/share/nginx/html

  mysql:
    # image: mysql:5.7
    image: mysql:5.6
    platform: linux/x86_64
    container_name: lnmp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${BASE_DIR}/mysql-backup_restore:/var/backup_restore
      - ${BASE_DIR}/mysql-data:/var/lib/mysql
      - ${BASE_DIR}/mysql-conf:/etc/mysql/conf.d
    # command: --explicit_defaults_for_timestamp

volumes:
  html:
  mysql-data:
  nginx-conf:
  mysql-conf:
